// BoardKey - Keyboard Layout Data
// Physical keyboard structures, character mappings, and layout metadata

// ============================================================================
// Physical Layouts
// ============================================================================
// Each layout is an array of rows. Each row is an array of key objects or spacers.
// Key object: { code: string, width: number, label?: string, modifier?: boolean }
// Spacer object: { spacer: number }

const ansiRows = [
  // Row 0: Function row
  [
    { code: 'Escape', width: 1, label: 'Esc' },
    { spacer: 0.75 },
    { code: 'F1', width: 1 },
    { code: 'F2', width: 1 },
    { code: 'F3', width: 1 },
    { code: 'F4', width: 1 },
    { spacer: 0.5 },
    { code: 'F5', width: 1 },
    { code: 'F6', width: 1 },
    { code: 'F7', width: 1 },
    { code: 'F8', width: 1 },
    { spacer: 0.5 },
    { code: 'F9', width: 1 },
    { code: 'F10', width: 1 },
    { code: 'F11', width: 1 },
    { code: 'F12', width: 1 },
  ],
  // Row 1: Number row
  [
    { code: 'Backquote', width: 1 },
    { code: 'Digit1', width: 1 },
    { code: 'Digit2', width: 1 },
    { code: 'Digit3', width: 1 },
    { code: 'Digit4', width: 1 },
    { code: 'Digit5', width: 1 },
    { code: 'Digit6', width: 1 },
    { code: 'Digit7', width: 1 },
    { code: 'Digit8', width: 1 },
    { code: 'Digit9', width: 1 },
    { code: 'Digit0', width: 1 },
    { code: 'Minus', width: 1 },
    { code: 'Equal', width: 1 },
    { code: 'Backspace', width: 2, label: '\u232b' },
  ],
  // Row 2: Top letter row
  [
    { code: 'Tab', width: 1.5, label: 'Tab' },
    { code: 'KeyQ', width: 1 },
    { code: 'KeyW', width: 1 },
    { code: 'KeyE', width: 1 },
    { code: 'KeyR', width: 1 },
    { code: 'KeyT', width: 1 },
    { code: 'KeyY', width: 1 },
    { code: 'KeyU', width: 1 },
    { code: 'KeyI', width: 1 },
    { code: 'KeyO', width: 1 },
    { code: 'KeyP', width: 1 },
    { code: 'BracketLeft', width: 1 },
    { code: 'BracketRight', width: 1 },
    { code: 'Backslash', width: 1.5 },
  ],
  // Row 3: Home row
  [
    { code: 'CapsLock', width: 1.75, label: 'Caps' },
    { code: 'KeyA', width: 1 },
    { code: 'KeyS', width: 1 },
    { code: 'KeyD', width: 1 },
    { code: 'KeyF', width: 1 },
    { code: 'KeyG', width: 1 },
    { code: 'KeyH', width: 1 },
    { code: 'KeyJ', width: 1 },
    { code: 'KeyK', width: 1 },
    { code: 'KeyL', width: 1 },
    { code: 'Semicolon', width: 1 },
    { code: 'Quote', width: 1 },
    { code: 'Enter', width: 2.25, label: 'Enter' },
  ],
  // Row 4: Bottom row
  [
    { code: 'ShiftLeft', width: 2.25, label: 'Shift', modifier: true },
    { code: 'KeyZ', width: 1 },
    { code: 'KeyX', width: 1 },
    { code: 'KeyC', width: 1 },
    { code: 'KeyV', width: 1 },
    { code: 'KeyB', width: 1 },
    { code: 'KeyN', width: 1 },
    { code: 'KeyM', width: 1 },
    { code: 'Comma', width: 1 },
    { code: 'Period', width: 1 },
    { code: 'Slash', width: 1 },
    { code: 'ShiftRight', width: 2.75, label: 'Shift', modifier: true },
  ],
  // Row 5: Bottom modifier row
  [
    { code: 'ControlLeft', width: 1.25, label: 'Ctrl', modifier: true },
    { code: 'MetaLeft', width: 1.25, label: 'Win', modifier: true },
    { code: 'AltLeft', width: 1.25, label: 'Alt', modifier: true },
    { code: 'Space', width: 6.25, label: '' },
    { code: 'AltRight', width: 1.25, label: 'Alt', modifier: true },
    { code: 'MetaRight', width: 1.25, label: 'Win', modifier: true },
    { code: 'ContextMenu', width: 1.25, label: 'Menu' },
    { code: 'ControlRight', width: 1.25, label: 'Ctrl', modifier: true },
  ],
];

const isoRows = [
  // Row 0: Function row (same as ANSI)
  ansiRows[0],
  // Row 1: Number row (same as ANSI)
  ansiRows[1],
  // Row 2: Top letter row (same as ANSI)
  ansiRows[2],
  // Row 3: Home row (same as ANSI)
  ansiRows[3],
  // Row 4: Bottom row - ISO has smaller left shift + IntlBackslash key
  [
    { code: 'ShiftLeft', width: 1.25, label: 'Shift', modifier: true },
    { code: 'IntlBackslash', width: 1 },
    { code: 'KeyZ', width: 1 },
    { code: 'KeyX', width: 1 },
    { code: 'KeyC', width: 1 },
    { code: 'KeyV', width: 1 },
    { code: 'KeyB', width: 1 },
    { code: 'KeyN', width: 1 },
    { code: 'KeyM', width: 1 },
    { code: 'Comma', width: 1 },
    { code: 'Period', width: 1 },
    { code: 'Slash', width: 1 },
    { code: 'ShiftRight', width: 2.75, label: 'Shift', modifier: true },
  ],
  // Row 5: Bottom modifier row (same as ANSI)
  ansiRows[5],
];

const jisRows = [
  // Row 0: Function row (same as ANSI)
  ansiRows[0],
  // Row 1: Number row - Backspace narrower, IntlYen key added
  [
    { code: 'Backquote', width: 1 },
    { code: 'Digit1', width: 1 },
    { code: 'Digit2', width: 1 },
    { code: 'Digit3', width: 1 },
    { code: 'Digit4', width: 1 },
    { code: 'Digit5', width: 1 },
    { code: 'Digit6', width: 1 },
    { code: 'Digit7', width: 1 },
    { code: 'Digit8', width: 1 },
    { code: 'Digit9', width: 1 },
    { code: 'Digit0', width: 1 },
    { code: 'Minus', width: 1 },
    { code: 'Equal', width: 1 },
    { code: 'IntlYen', width: 1 },
    { code: 'Backspace', width: 1, label: '\u232b' },
  ],
  // Row 2: Top letter row (same as ANSI)
  ansiRows[2],
  // Row 3: Home row - Enter narrower, IntlHash key added
  [
    { code: 'CapsLock', width: 1.75, label: 'Caps' },
    { code: 'KeyA', width: 1 },
    { code: 'KeyS', width: 1 },
    { code: 'KeyD', width: 1 },
    { code: 'KeyF', width: 1 },
    { code: 'KeyG', width: 1 },
    { code: 'KeyH', width: 1 },
    { code: 'KeyJ', width: 1 },
    { code: 'KeyK', width: 1 },
    { code: 'KeyL', width: 1 },
    { code: 'Semicolon', width: 1 },
    { code: 'Quote', width: 1 },
    { code: 'IntlHash', width: 1 },
    { code: 'Enter', width: 1.25, label: 'Enter' },
  ],
  // Row 4: Bottom row - ISO-style with IntlBackslash
  [
    { code: 'ShiftLeft', width: 1.25, label: 'Shift', modifier: true },
    { code: 'IntlBackslash', width: 1 },
    { code: 'KeyZ', width: 1 },
    { code: 'KeyX', width: 1 },
    { code: 'KeyC', width: 1 },
    { code: 'KeyV', width: 1 },
    { code: 'KeyB', width: 1 },
    { code: 'KeyN', width: 1 },
    { code: 'KeyM', width: 1 },
    { code: 'Comma', width: 1 },
    { code: 'Period', width: 1 },
    { code: 'Slash', width: 1 },
    { code: 'ShiftRight', width: 2.75, label: 'Shift', modifier: true },
  ],
  // Row 5: Bottom modifier row - JIS has extra keys, narrower space
  [
    { code: 'ControlLeft', width: 1.25, label: 'Ctrl', modifier: true },
    { code: 'MetaLeft', width: 1.25, label: 'Win', modifier: true },
    { code: 'AltLeft', width: 1.25, label: 'Alt', modifier: true },
    { code: 'NonConvert', width: 1, label: '\u7121\u5909\u63db' },
    { code: 'Space', width: 3.25, label: '' },
    { code: 'Convert', width: 1, label: '\u5909\u63db' },
    { code: 'KanaMode', width: 1, label: '\u304b\u306a' },
    { code: 'AltRight', width: 1.25, label: 'Alt', modifier: true },
    { code: 'MetaRight', width: 1.25, label: 'Win', modifier: true },
    { code: 'ContextMenu', width: 1.25, label: 'Menu' },
    { code: 'ControlRight', width: 1.25, label: 'Ctrl', modifier: true },
  ],
];

// Mac-specific bottom modifier rows
// Mac order: fn, Control, Option, Command, Space, Command, Option
// (fn is a hardware key that doesn't fire KeyboardEvent — visual only)
const macAnsiBottomRow = [
  { code: 'Fn', width: 1.25, label: 'fn' },
  { code: 'ControlLeft', width: 1.25, modifier: true },
  { code: 'AltLeft', width: 1.25, modifier: true },
  { code: 'MetaLeft', width: 1.25, modifier: true },
  { code: 'Space', width: 6.25, label: '' },
  { code: 'MetaRight', width: 1.25, modifier: true },
  { code: 'AltRight', width: 1.25, modifier: true },
  { code: 'ControlRight', width: 1.25, modifier: true },
];

const macJisBottomRow = [
  { code: 'Fn', width: 1.25, label: 'fn' },
  { code: 'ControlLeft', width: 1.25, modifier: true },
  { code: 'AltLeft', width: 1.25, modifier: true },
  { code: 'MetaLeft', width: 1.25, modifier: true },
  { code: 'NonConvert', width: 1, label: '\u82f1\u6570' },
  { code: 'Space', width: 4.25, label: '' },
  { code: 'Convert', width: 1, label: '\u304b\u306a' },
  { code: 'MetaRight', width: 1.25, modifier: true },
  { code: 'AltRight', width: 1.25, modifier: true },
  { code: 'ControlRight', width: 1.25, modifier: true },
];

// Navigation cluster, arrow keys, and numpad extensions per row
const navExtension = [
  // Row 0: fn row
  [
    { spacer: 0.5 },
    { code: 'PrintScreen', width: 1, label: 'PrtSc' },
    { code: 'ScrollLock', width: 1, label: 'ScrLk' },
    { code: 'Pause', width: 1, label: 'Pause' },
  ],
  // Row 1: number row
  [
    { spacer: 0.5 },
    { code: 'Insert', width: 1, label: 'Ins' },
    { code: 'Home', width: 1, label: 'Home' },
    { code: 'PageUp', width: 1, label: 'PgUp' },
  ],
  // Row 2: top letter row
  [
    { spacer: 0.5 },
    { code: 'Delete', width: 1, label: 'Del' },
    { code: 'End', width: 1, label: 'End' },
    { code: 'PageDown', width: 1, label: 'PgDn' },
  ],
  // Row 3: home row — empty nav area
  [],
  // Row 4: bottom row — up arrow centered
  [
    { spacer: 1.5 },
    { code: 'ArrowUp', width: 1, label: '\u2191' },
  ],
  // Row 5: modifier row — arrow keys
  [
    { spacer: 0.5 },
    { code: 'ArrowLeft', width: 1, label: '\u2190' },
    { code: 'ArrowDown', width: 1, label: '\u2193' },
    { code: 'ArrowRight', width: 1, label: '\u2192' },
  ],
];

const numpadExtension = [
  // Row 0: fn row — nothing
  [],
  // Row 1: number row
  [
    { spacer: 0.25 },
    { code: 'NumLock', width: 1, label: 'Num' },
    { code: 'NumpadDivide', width: 1, label: '/' },
    { code: 'NumpadMultiply', width: 1, label: '*' },
    { code: 'NumpadSubtract', width: 1, label: '\u2212' },
  ],
  // Row 2: top letter row
  [
    { spacer: 0.25 },
    { code: 'Numpad7', width: 1, label: '7' },
    { code: 'Numpad8', width: 1, label: '8' },
    { code: 'Numpad9', width: 1, label: '9' },
    { code: 'NumpadAdd', width: 1, label: '+' },
  ],
  // Row 3: home row
  [
    { spacer: 0.25 },
    { code: 'Numpad4', width: 1, label: '4' },
    { code: 'Numpad5', width: 1, label: '5' },
    { code: 'Numpad6', width: 1, label: '6' },
  ],
  // Row 4: bottom row
  [
    { spacer: 0.25 },
    { code: 'Numpad1', width: 1, label: '1' },
    { code: 'Numpad2', width: 1, label: '2' },
    { code: 'Numpad3', width: 1, label: '3' },
    { code: 'NumpadEnter', width: 1, label: 'Ent' },
  ],
  // Row 5: modifier row
  [
    { spacer: 0.25 },
    { code: 'Numpad0', width: 2, label: '0' },
    { code: 'NumpadDecimal', width: 1, label: '.' },
  ],
];

export const physicalLayouts = {
  ansi: ansiRows,
  iso: isoRows,
  jis: jisRows,
};

/**
 * Get the physical layout rows, with platform-specific modifier row,
 * plus navigation cluster, arrow keys, and numpad.
 * @param {string} physicalType - 'ansi', 'iso', 'jis'
 * @param {string} platform - 'mac', 'windows', 'linux'
 * @returns {Array} array of rows
 */
export function getPhysicalLayout(physicalType, platform) {
  const base = physicalLayouts[physicalType] || physicalLayouts.ansi;

  let rows;
  if (platform === 'mac') {
    const macRow = physicalType === 'jis' ? macJisBottomRow : macAnsiBottomRow;
    rows = [...base.slice(0, -1), macRow];
  } else {
    rows = [...base];
  }

  // Append navigation cluster, arrows, and numpad to each row
  return rows.map((row, i) => [
    ...row,
    ...(navExtension[i] || []),
    ...(numpadExtension[i] || []),
  ]);
}

// ============================================================================
// Character Mappings
// ============================================================================
// Each layout maps KeyboardEvent.code to [normal, shift, altGr?, shiftAltGr?]

export const layoutMappings = {

  // --------------------------------------------------------------------------
  // US English (QWERTY) - ANSI
  // --------------------------------------------------------------------------
  'en-us': {
    'Backquote': ['`', '~'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '@'],
    'Digit3': ['3', '#'],
    'Digit4': ['4', '$'],
    'Digit5': ['5', '%'],
    'Digit6': ['6', '^'],
    'Digit7': ['7', '&'],
    'Digit8': ['8', '*'],
    'Digit9': ['9', '('],
    'Digit0': ['0', ')'],
    'Minus': ['-', '_'],
    'Equal': ['=', '+'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['[', '{'],
    'BracketRight': [']', '}'],
    'Backslash': ['\\', '|'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': [';', ':'],
    'Quote': ["'", '"'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', '<'],
    'Period': ['.', '>'],
    'Slash': ['/', '?'],
  },

  // --------------------------------------------------------------------------
  // UK English - ISO
  // --------------------------------------------------------------------------
  'en-gb': {
    'Backquote': ['`', '\u00ac', '\u00a6'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '"'],
    'Digit3': ['3', '\u00a3'],
    'Digit4': ['4', '$', '\u20ac'],
    'Digit5': ['5', '%'],
    'Digit6': ['6', '^'],
    'Digit7': ['7', '&'],
    'Digit8': ['8', '*'],
    'Digit9': ['9', '('],
    'Digit0': ['0', ')'],
    'Minus': ['-', '_'],
    'Equal': ['=', '+'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E', '\u00e9'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U', '\u00fa'],
    'KeyI': ['i', 'I', '\u00ed'],
    'KeyO': ['o', 'O', '\u00f3'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['[', '{'],
    'BracketRight': [']', '}'],
    'Backslash': ['#', '~'],
    'KeyA': ['a', 'A', '\u00e1'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': [';', ':'],
    'Quote': ["'", '@'],
    'IntlBackslash': ['\\', '|'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', '<'],
    'Period': ['.', '>'],
    'Slash': ['/', '?'],
  },

  // --------------------------------------------------------------------------
  // German (QWERTZ) - ISO
  // --------------------------------------------------------------------------
  'de-de': {
    'Backquote': ['^', '\u00b0'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '"', '\u00b2'],
    'Digit3': ['3', '\u00a7', '\u00b3'],
    'Digit4': ['4', '$'],
    'Digit5': ['5', '%'],
    'Digit6': ['6', '&'],
    'Digit7': ['7', '/', '{'],
    'Digit8': ['8', '(', '['],
    'Digit9': ['9', ')', ']'],
    'Digit0': ['0', '=', '}'],
    'Minus': ['\u00df', '?', '\\'],
    'Equal': ['\u00b4', '`'],
    'KeyQ': ['q', 'Q', '@'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E', '\u20ac'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['z', 'Z'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['\u00fc', '\u00dc'],
    'BracketRight': ['+', '*', '~'],
    'Backslash': ['#', "'"],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': ['\u00f6', '\u00d6'],
    'Quote': ['\u00e4', '\u00c4'],
    'IntlBackslash': ['<', '>', '|'],
    'KeyZ': ['y', 'Y'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M', '\u00b5'],
    'Comma': [',', ';'],
    'Period': ['.', ':'],
    'Slash': ['-', '_'],
  },

  // --------------------------------------------------------------------------
  // French (AZERTY) - ISO
  // --------------------------------------------------------------------------
  'fr-fr': {
    'Backquote': ['\u00b2', '\u00b3'],
    'Digit1': ['&', '1'],
    'Digit2': ['\u00e9', '2', '~'],
    'Digit3': ['"', '3', '#'],
    'Digit4': ["'", '4', '{'],
    'Digit5': ['(', '5', '['],
    'Digit6': ['-', '6', '|'],
    'Digit7': ['\u00e8', '7', '`'],
    'Digit8': ['_', '8', '\\'],
    'Digit9': ['\u00e7', '9', '^'],
    'Digit0': ['\u00e0', '0', '@'],
    'Minus': [')', '\u00b0', ']'],
    'Equal': ['=', '+', '}'],
    'KeyQ': ['a', 'A'],
    'KeyW': ['z', 'Z'],
    'KeyE': ['e', 'E', '\u20ac'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['^', '\u00a8'],
    'BracketRight': ['$', '\u00a3', '\u00a4'],
    'Backslash': ['*', '\u00b5'],
    'KeyA': ['q', 'Q'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': ['m', 'M'],
    'Quote': ['\u00f9', '%'],
    'IntlBackslash': ['<', '>'],
    'KeyZ': ['w', 'W'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': [',', '?'],
    'Comma': [';', '.'],
    'Period': [':', '/'],
    'Slash': ['!', '\u00a7'],
  },

  // --------------------------------------------------------------------------
  // Spanish (Spain) - ISO
  // --------------------------------------------------------------------------
  'es-es': {
    'Backquote': ['\u00ba', '\u00aa', '\\'],
    'Digit1': ['1', '!', '|'],
    'Digit2': ['2', '"', '@'],
    'Digit3': ['3', '\u00b7', '#'],
    'Digit4': ['4', '$', '~'],
    'Digit5': ['5', '%', '\u20ac'],
    'Digit6': ['6', '&', '\u00ac'],
    'Digit7': ['7', '/'],
    'Digit8': ['8', '('],
    'Digit9': ['9', ')'],
    'Digit0': ['0', '='],
    'Minus': ["'", '?'],
    'Equal': ['\u00a1', '\u00bf'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E', '\u20ac'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['`', '^', '['],
    'BracketRight': ['+', '*', ']'],
    'Backslash': ['\u00e7', '\u00c7', '}'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': ['\u00f1', '\u00d1'],
    'Quote': ['\u00b4', '\u00a8', '{'],
    'IntlBackslash': ['<', '>'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', ';'],
    'Period': ['.', ':'],
    'Slash': ['-', '_'],
  },

  // --------------------------------------------------------------------------
  // Italian - ISO
  // --------------------------------------------------------------------------
  'it-it': {
    'Backquote': ['\\', '|'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '"'],
    'Digit3': ['3', '\u00a3', '#'],
    'Digit4': ['4', '$'],
    'Digit5': ['5', '%', '\u20ac'],
    'Digit6': ['6', '&'],
    'Digit7': ['7', '/'],
    'Digit8': ['8', '('],
    'Digit9': ['9', ')'],
    'Digit0': ['0', '='],
    'Minus': ["'", '?'],
    'Equal': ['\u00ec', '^'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E', '\u20ac'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['\u00e8', '\u00e9', '[', '{'],
    'BracketRight': ['+', '*', ']', '}'],
    'Backslash': ['\u00f9', '\u00a7'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': ['\u00f2', '\u00e7', '@'],
    'Quote': ['\u00e0', '\u00b0', '#'],
    'IntlBackslash': ['<', '>'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', ';'],
    'Period': ['.', ':'],
    'Slash': ['-', '_'],
  },

  // --------------------------------------------------------------------------
  // Brazilian Portuguese (ABNT2) - ISO
  // --------------------------------------------------------------------------
  'pt-br': {
    'Backquote': ["'", '"'],
    'Digit1': ['1', '!', '\u00b9'],
    'Digit2': ['2', '@', '\u00b2'],
    'Digit3': ['3', '#', '\u00b3'],
    'Digit4': ['4', '$', '\u00a3'],
    'Digit5': ['5', '%', '\u00a2'],
    'Digit6': ['6', '\u00a8', '\u00ac'],
    'Digit7': ['7', '&'],
    'Digit8': ['8', '*'],
    'Digit9': ['9', '('],
    'Digit0': ['0', ')'],
    'Minus': ['-', '_'],
    'Equal': ['=', '+', '\u00a7'],
    'KeyQ': ['q', 'Q', '/'],
    'KeyW': ['w', 'W', '?'],
    'KeyE': ['e', 'E', '\u00b0'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['\u00b4', '`'],
    'BracketRight': ['[', '{', '\u00aa'],
    'Backslash': [']', '}', '\u00ba'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': ['\u00e7', '\u00c7'],
    'Quote': ['~', '^'],
    'IntlBackslash': ['\\', '|'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', '<'],
    'Period': ['.', '>'],
    'Slash': [';', ':'],
    'IntlRo': ['/', '?'],
  },

  // --------------------------------------------------------------------------
  // Russian (\u0419\u0426\u0423\u041a\u0415\u041d) - ISO
  // --------------------------------------------------------------------------
  'ru-ru': {
    'Backquote': ['\u0451', '\u0401'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '"'],
    'Digit3': ['3', '\u2116'],
    'Digit4': ['4', ';'],
    'Digit5': ['5', '%'],
    'Digit6': ['6', ':'],
    'Digit7': ['7', '?'],
    'Digit8': ['8', '*'],
    'Digit9': ['9', '('],
    'Digit0': ['0', ')'],
    'Minus': ['-', '_'],
    'Equal': ['=', '+'],
    'KeyQ': ['\u0439', '\u0419'],
    'KeyW': ['\u0446', '\u0426'],
    'KeyE': ['\u0443', '\u0423'],
    'KeyR': ['\u043a', '\u041a'],
    'KeyT': ['\u0435', '\u0415'],
    'KeyY': ['\u043d', '\u041d'],
    'KeyU': ['\u0433', '\u0413'],
    'KeyI': ['\u0448', '\u0428'],
    'KeyO': ['\u0449', '\u0429'],
    'KeyP': ['\u0437', '\u0417'],
    'BracketLeft': ['\u0445', '\u0425'],
    'BracketRight': ['\u044a', '\u042a'],
    'Backslash': ['\\', '/'],
    'KeyA': ['\u0444', '\u0424'],
    'KeyS': ['\u044b', '\u042b'],
    'KeyD': ['\u0432', '\u0412'],
    'KeyF': ['\u0430', '\u0410'],
    'KeyG': ['\u043f', '\u041f'],
    'KeyH': ['\u0440', '\u0420'],
    'KeyJ': ['\u043e', '\u041e'],
    'KeyK': ['\u043b', '\u041b'],
    'KeyL': ['\u0434', '\u0414'],
    'Semicolon': ['\u0436', '\u0416'],
    'Quote': ['\u044d', '\u042d'],
    'IntlBackslash': ['\\', '/'],
    'KeyZ': ['\u044f', '\u042f'],
    'KeyX': ['\u0447', '\u0427'],
    'KeyC': ['\u0441', '\u0421'],
    'KeyV': ['\u043c', '\u041c'],
    'KeyB': ['\u0438', '\u0418'],
    'KeyN': ['\u0442', '\u0422'],
    'KeyM': ['\u044c', '\u042c'],
    'Comma': ['\u0431', '\u0411'],
    'Period': ['\u044e', '\u042e'],
    'Slash': ['.', ','],
  },

  // --------------------------------------------------------------------------
  // Japanese - ANSI (same characters as US, different punctuation on some keys)
  // --------------------------------------------------------------------------
  'ja-jp': {
    'Backquote': ['`', '~'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '@'],
    'Digit3': ['3', '#'],
    'Digit4': ['4', '$'],
    'Digit5': ['5', '%'],
    'Digit6': ['6', '^'],
    'Digit7': ['7', '&'],
    'Digit8': ['8', '*'],
    'Digit9': ['9', '('],
    'Digit0': ['0', ')'],
    'Minus': ['-', '_'],
    'Equal': ['=', '+'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['[', '{'],
    'BracketRight': [']', '}'],
    'Backslash': ['\\', '|'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': [';', ':'],
    'Quote': ["'", '"'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', '<'],
    'Period': ['.', '>'],
    'Slash': ['/', '?'],
    'IntlYen': ['\u00a5', '|'],
    'IntlHash': ['\\', '_'],
    'IntlRo': ['\\', '_'],
  },

  // --------------------------------------------------------------------------
  // Korean - ANSI (same physical layout as US; Korean IME handles Hangul)
  // --------------------------------------------------------------------------
  'ko-kr': {
    'Backquote': ['`', '~'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '@'],
    'Digit3': ['3', '#'],
    'Digit4': ['4', '$'],
    'Digit5': ['5', '%'],
    'Digit6': ['6', '^'],
    'Digit7': ['7', '&'],
    'Digit8': ['8', '*'],
    'Digit9': ['9', '('],
    'Digit0': ['0', ')'],
    'Minus': ['-', '_'],
    'Equal': ['=', '+'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['[', '{'],
    'BracketRight': [']', '}'],
    'Backslash': ['\\', '|'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': [';', ':'],
    'Quote': ["'", '"'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', '<'],
    'Period': ['.', '>'],
    'Slash': ['/', '?'],
  },

  // --------------------------------------------------------------------------
  // Swedish - ISO
  // --------------------------------------------------------------------------
  'sv-se': {
    'Backquote': ['\u00a7', '\u00bd'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '"', '@'],
    'Digit3': ['3', '#', '\u00a3'],
    'Digit4': ['4', '\u00a4', '$'],
    'Digit5': ['5', '%', '\u20ac'],
    'Digit6': ['6', '&'],
    'Digit7': ['7', '/', '{'],
    'Digit8': ['8', '(', '['],
    'Digit9': ['9', ')', ']'],
    'Digit0': ['0', '=', '}'],
    'Minus': ['+', '?', '\\'],
    'Equal': ['\u00b4', '`'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E', '\u20ac'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['\u00e5', '\u00c5'],
    'BracketRight': ['\u00a8', '^', '~'],
    'Backslash': ["'", '*'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': ['\u00f6', '\u00d6'],
    'Quote': ['\u00e4', '\u00c4'],
    'IntlBackslash': ['<', '>', '|'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', ';'],
    'Period': ['.', ':'],
    'Slash': ['-', '_'],
  },

  // --------------------------------------------------------------------------
  // Norwegian - ISO
  // --------------------------------------------------------------------------
  'nb-no': {
    'Backquote': ['|', '\u00a7'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '"', '@'],
    'Digit3': ['3', '#', '\u00a3'],
    'Digit4': ['4', '\u00a4', '$'],
    'Digit5': ['5', '%', '\u20ac'],
    'Digit6': ['6', '&'],
    'Digit7': ['7', '/', '{'],
    'Digit8': ['8', '(', '['],
    'Digit9': ['9', ')', ']'],
    'Digit0': ['0', '=', '}'],
    'Minus': ['+', '?'],
    'Equal': ['\\', '`', '\u00b4'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E', '\u20ac'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['\u00e5', '\u00c5'],
    'BracketRight': ['\u00a8', '^', '~'],
    'Backslash': ["'", '*'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': ['\u00f8', '\u00d8'],
    'Quote': ['\u00e6', '\u00c6'],
    'IntlBackslash': ['<', '>'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', ';'],
    'Period': ['.', ':'],
    'Slash': ['-', '_'],
  },

  // --------------------------------------------------------------------------
  // Danish - ISO
  // --------------------------------------------------------------------------
  'da-dk': {
    'Backquote': ['\u00bd', '\u00a7'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '"', '@'],
    'Digit3': ['3', '#', '\u00a3'],
    'Digit4': ['4', '\u00a4', '$'],
    'Digit5': ['5', '%', '\u20ac'],
    'Digit6': ['6', '&'],
    'Digit7': ['7', '/', '{'],
    'Digit8': ['8', '(', '['],
    'Digit9': ['9', ')', ']'],
    'Digit0': ['0', '=', '}'],
    'Minus': ['+', '?'],
    'Equal': ['\u00b4', '`', '|'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E', '\u20ac'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['\u00e5', '\u00c5'],
    'BracketRight': ['\u00a8', '^', '~'],
    'Backslash': ["'", '*'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': ['\u00e6', '\u00c6'],
    'Quote': ['\u00f8', '\u00d8'],
    'IntlBackslash': ['<', '>', '\\'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', ';'],
    'Period': ['.', ':'],
    'Slash': ['-', '_'],
  },

  // --------------------------------------------------------------------------
  // Dutch - ISO
  // --------------------------------------------------------------------------
  'nl-nl': {
    'Backquote': ['@', '\u00a7', '\u00ac'],
    'Digit1': ['1', '!', '\u00b9'],
    'Digit2': ['2', '"', '\u00b2'],
    'Digit3': ['3', '#', '\u00b3'],
    'Digit4': ['4', '$', '\u00bc'],
    'Digit5': ['5', '%', '\u00bd'],
    'Digit6': ['6', '&', '\u00be'],
    'Digit7': ['7', '_', '\u00a3'],
    'Digit8': ['8', '(', '{'],
    'Digit9': ['9', ')', '}'],
    'Digit0': ['0', "'"],
    'Minus': ['/', '?', '\\'],
    'Equal': ['\u00b0', '~', '\u00b8'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E', '\u20ac'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['\u00a8', '^'],
    'BracketRight': ['*', '|'],
    'Backslash': ['<', '>'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S', '\u00df'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': ['+', '\u00b1'],
    'Quote': ['\u00b4', '`'],
    'IntlBackslash': [']', '[', '|'],
    'KeyZ': ['z', 'Z', '\u00ab'],
    'KeyX': ['x', 'X', '\u00bb'],
    'KeyC': ['c', 'C', '\u00a2'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M', '\u00b5'],
    'Comma': [',', ';'],
    'Period': ['.', ':', '\u00b7'],
    'Slash': ['-', '='],
  },

  // --------------------------------------------------------------------------
  // Polish (Programmers) - ISO
  // --------------------------------------------------------------------------
  'pl-pl': {
    'Backquote': ['`', '~'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '@'],
    'Digit3': ['3', '#'],
    'Digit4': ['4', '$'],
    'Digit5': ['5', '%'],
    'Digit6': ['6', '^'],
    'Digit7': ['7', '&'],
    'Digit8': ['8', '*'],
    'Digit9': ['9', '('],
    'Digit0': ['0', ')'],
    'Minus': ['-', '_'],
    'Equal': ['=', '+'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E', '\u0119', '\u0118'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O', '\u00f3', '\u00d3'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['[', '{'],
    'BracketRight': [']', '}'],
    'Backslash': ['\\', '|'],
    'KeyA': ['a', 'A', '\u0105', '\u0104'],
    'KeyS': ['s', 'S', '\u015b', '\u015a'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L', '\u0142', '\u0141'],
    'Semicolon': [';', ':'],
    'Quote': ["'", '"'],
    'IntlBackslash': ['\\', '|'],
    'KeyZ': ['z', 'Z', '\u017c', '\u017b'],
    'KeyX': ['x', 'X', '\u017a', '\u0179'],
    'KeyC': ['c', 'C', '\u0107', '\u0106'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N', '\u0144', '\u0143'],
    'KeyM': ['m', 'M'],
    'Comma': [',', '<'],
    'Period': ['.', '>'],
    'Slash': ['/', '?'],
  },

  // --------------------------------------------------------------------------
  // Czech (QWERTZ) - ISO
  // --------------------------------------------------------------------------
  'cs-cz': {
    'Backquote': [';', '\u00b0'],
    'Digit1': ['+', '1', '~'],
    'Digit2': ['\u011b', '2', '\u02c7'],
    'Digit3': ['\u0161', '3', '^'],
    'Digit4': ['\u010d', '4', '\u02d8'],
    'Digit5': ['\u0159', '5', '\u00b0'],
    'Digit6': ['\u017e', '6', '\u02db'],
    'Digit7': ['\u00fd', '7', '`'],
    'Digit8': ['\u00e1', '8', '\u02d9'],
    'Digit9': ['\u00ed', '9', '\u00b4'],
    'Digit0': ['\u00e9', '0', '\u02dd'],
    'Minus': ['=', '%', '\u00a8'],
    'Equal': ['\u00b4', '\u02c7', '\u00b8'],
    'KeyQ': ['q', 'Q', '\\'],
    'KeyW': ['w', 'W', '|'],
    'KeyE': ['e', 'E', '\u20ac'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['z', 'Z'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['\u00fa', '/', '\u00f7'],
    'BracketRight': [')', '(', '\u00d7'],
    'Backslash': ['\u00a8', "'", '\u00a4'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S', '\u0111'],
    'KeyD': ['d', 'D', '\u0110'],
    'KeyF': ['f', 'F', '['],
    'KeyG': ['g', 'G', ']'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K', '\u0142'],
    'KeyL': ['l', 'L', '\u0141'],
    'Semicolon': ['\u016f', '"', '$'],
    'Quote': ['\u00a7', '!', '\u00df'],
    'IntlBackslash': ['\\', '|'],
    'KeyZ': ['y', 'Y'],
    'KeyX': ['x', 'X', '#'],
    'KeyC': ['c', 'C', '&'],
    'KeyV': ['v', 'V', '@'],
    'KeyB': ['b', 'B', '{'],
    'KeyN': ['n', 'N', '}'],
    'KeyM': ['m', 'M'],
    'Comma': [',', '?', '<'],
    'Period': ['.', ':', '>'],
    'Slash': ['-', '_', '*'],
  },

  // --------------------------------------------------------------------------
  // Turkish Q - ISO
  // --------------------------------------------------------------------------
  'tr-tr': {
    'Backquote': ['"', '\u00e9', '<'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', "'", '\u00a3'],
    'Digit3': ['3', '^', '#'],
    'Digit4': ['4', '+', '$'],
    'Digit5': ['5', '%', '\u00bd'],
    'Digit6': ['6', '&'],
    'Digit7': ['7', '/', '{'],
    'Digit8': ['8', '(', '['],
    'Digit9': ['9', ')', ']'],
    'Digit0': ['0', '=', '}'],
    'Minus': ['*', '?', '\\'],
    'Equal': ['-', '_', '|'],
    'KeyQ': ['q', 'Q', '@'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E', '\u20ac'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['\u0131', 'I', '\u00ec'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['\u011f', '\u011e', '\u00a8'],
    'BracketRight': ['\u00fc', '\u00dc', '~'],
    'Backslash': [',', ';', '`'],
    'KeyA': ['a', 'A', '\u00e6'],
    'KeyS': ['s', 'S', '\u00df'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': ['\u015f', '\u015e', '\u00b4'],
    'Quote': ['i', '\u0130'],
    'IntlBackslash': ['<', '>', '|'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': ['\u00f6', '\u00d6'],
    'Period': ['\u00e7', '\u00c7'],
    'Slash': ['.', ':'],
  },

  // --------------------------------------------------------------------------
  // Arabic (Saudi Arabia) - ISO
  // --------------------------------------------------------------------------
  'ar-sa': {
    'Backquote': ['\u0630', '\u0651'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '@'],
    'Digit3': ['3', '#'],
    'Digit4': ['4', '$'],
    'Digit5': ['5', '%'],
    'Digit6': ['6', '^'],
    'Digit7': ['7', '&'],
    'Digit8': ['8', '*'],
    'Digit9': ['9', '('],
    'Digit0': ['0', ')'],
    'Minus': ['-', '_'],
    'Equal': ['=', '+'],
    'KeyQ': ['\u0636', '\u064e'],
    'KeyW': ['\u0635', '\u064b'],
    'KeyE': ['\u062b', '\u064f'],
    'KeyR': ['\u0642', '\u064c'],
    'KeyT': ['\u0641', '\u0644\u0625'],
    'KeyY': ['\u063a', '\u0625'],
    'KeyU': ['\u0639', '\u2018'],
    'KeyI': ['\u0647', '\u00f7'],
    'KeyO': ['\u062e', '\u00d7'],
    'KeyP': ['\u062d', '\u061b'],
    'BracketLeft': ['\u062c', '<'],
    'BracketRight': ['\u062f', '>'],
    'Backslash': ['\\', '|'],
    'KeyA': ['\u0634', '\u0650'],
    'KeyS': ['\u0633', '\u064d'],
    'KeyD': ['\u064a', '['],
    'KeyF': ['\u0628', ']'],
    'KeyG': ['\u0644', '\u0644\u0623'],
    'KeyH': ['\u0627', '\u0623'],
    'KeyJ': ['\u062a', '\u0640'],
    'KeyK': ['\u0646', '\u060c'],
    'KeyL': ['\u0645', '/'],
    'Semicolon': ['\u0643', ':'],
    'Quote': ['\u0637', '"'],
    'IntlBackslash': ['\\', '|'],
    'KeyZ': ['\u0626', '~'],
    'KeyX': ['\u0621', '\u0652'],
    'KeyC': ['\u0624', '{'],
    'KeyV': ['\u0631', '}'],
    'KeyB': ['\u0644\u0627', '\u0644\u0622'],
    'KeyN': ['\u0649', '\u0622'],
    'KeyM': ['\u0629', "'"],
    'Comma': ['\u0648', ','],
    'Period': ['\u0632', '.'],
    'Slash': ['\u0638', '\u061f'],
  },

  // --------------------------------------------------------------------------
  // Hebrew - ISO
  // --------------------------------------------------------------------------
  'he-il': {
    'Backquote': [';', '~'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '@'],
    'Digit3': ['3', '#'],
    'Digit4': ['4', '$', '\u20aa'],
    'Digit5': ['5', '%'],
    'Digit6': ['6', '^'],
    'Digit7': ['7', '&'],
    'Digit8': ['8', '*'],
    'Digit9': ['9', '('],
    'Digit0': ['0', ')'],
    'Minus': ['-', '_'],
    'Equal': ['=', '+'],
    'KeyQ': ['/', 'Q'],
    'KeyW': ["'", 'W'],
    'KeyE': ['\u05e7', 'E'],
    'KeyR': ['\u05e8', 'R'],
    'KeyT': ['\u05d0', 'T'],
    'KeyY': ['\u05d8', 'Y'],
    'KeyU': ['\u05d5', 'U'],
    'KeyI': ['\u05df', 'I'],
    'KeyO': ['\u05dd', 'O'],
    'KeyP': ['\u05e4', 'P'],
    'BracketLeft': [']', '}'],
    'BracketRight': ['[', '{'],
    'Backslash': ['\\', '|'],
    'KeyA': ['\u05e9', 'A'],
    'KeyS': ['\u05d3', 'S'],
    'KeyD': ['\u05d2', 'D'],
    'KeyF': ['\u05db', 'F'],
    'KeyG': ['\u05e2', 'G'],
    'KeyH': ['\u05d9', 'H'],
    'KeyJ': ['\u05d7', 'J'],
    'KeyK': ['\u05dc', 'K'],
    'KeyL': ['\u05da', 'L'],
    'Semicolon': ['\u05e3', ':'],
    'Quote': [',', '"'],
    'IntlBackslash': ['\\', '|'],
    'KeyZ': ['\u05d6', 'Z'],
    'KeyX': ['\u05e1', 'X'],
    'KeyC': ['\u05d1', 'C'],
    'KeyV': ['\u05d4', 'V'],
    'KeyB': ['\u05e0', 'B'],
    'KeyN': ['\u05de', 'N'],
    'KeyM': ['\u05e6', 'M'],
    'Comma': ['\u05ea', '>'],
    'Period': ['\u05e5', '<'],
    'Slash': ['.', '?'],
  },

  // --------------------------------------------------------------------------
  // Chinese Traditional (Taiwan) - ANSI (same as US QWERTY)
  // --------------------------------------------------------------------------
  'zh-tw': {
    'Backquote': ['`', '~'],
    'Digit1': ['1', '!'],
    'Digit2': ['2', '@'],
    'Digit3': ['3', '#'],
    'Digit4': ['4', '$'],
    'Digit5': ['5', '%'],
    'Digit6': ['6', '^'],
    'Digit7': ['7', '&'],
    'Digit8': ['8', '*'],
    'Digit9': ['9', '('],
    'Digit0': ['0', ')'],
    'Minus': ['-', '_'],
    'Equal': ['=', '+'],
    'KeyQ': ['q', 'Q'],
    'KeyW': ['w', 'W'],
    'KeyE': ['e', 'E'],
    'KeyR': ['r', 'R'],
    'KeyT': ['t', 'T'],
    'KeyY': ['y', 'Y'],
    'KeyU': ['u', 'U'],
    'KeyI': ['i', 'I'],
    'KeyO': ['o', 'O'],
    'KeyP': ['p', 'P'],
    'BracketLeft': ['[', '{'],
    'BracketRight': [']', '}'],
    'Backslash': ['\\', '|'],
    'KeyA': ['a', 'A'],
    'KeyS': ['s', 'S'],
    'KeyD': ['d', 'D'],
    'KeyF': ['f', 'F'],
    'KeyG': ['g', 'G'],
    'KeyH': ['h', 'H'],
    'KeyJ': ['j', 'J'],
    'KeyK': ['k', 'K'],
    'KeyL': ['l', 'L'],
    'Semicolon': [';', ':'],
    'Quote': ["'", '"'],
    'KeyZ': ['z', 'Z'],
    'KeyX': ['x', 'X'],
    'KeyC': ['c', 'C'],
    'KeyV': ['v', 'V'],
    'KeyB': ['b', 'B'],
    'KeyN': ['n', 'N'],
    'KeyM': ['m', 'M'],
    'Comma': [',', '<'],
    'Period': ['.', '>'],
    'Slash': ['/', '?'],
  },
};

// ============================================================================
// Layout List (metadata)
// ============================================================================

export const layoutList = [
  { id: 'en-us', name: 'US English', region: 'United States', physical: 'ansi', lang: 'en' },
  { id: 'en-gb', name: 'UK English', region: 'United Kingdom', physical: 'iso', lang: 'en' },
  { id: 'de-de', name: 'German', region: 'Germany', physical: 'iso', lang: 'de' },
  { id: 'fr-fr', name: 'French', region: 'France', physical: 'iso', lang: 'fr' },
  { id: 'es-es', name: 'Spanish', region: 'Spain', physical: 'iso', lang: 'es' },
  { id: 'it-it', name: 'Italian', region: 'Italy', physical: 'iso', lang: 'it' },
  { id: 'pt-br', name: 'Portuguese', region: 'Brazil', physical: 'iso', lang: 'pt' },
  { id: 'ru-ru', name: 'Russian', region: 'Russia', physical: 'iso', lang: 'ru' },
  { id: 'ja-jp', name: 'Japanese', region: 'Japan', physical: 'ansi', lang: 'ja' },
  { id: 'ko-kr', name: 'Korean', region: 'South Korea', physical: 'ansi', lang: 'ko' },
  { id: 'sv-se', name: 'Swedish', region: 'Sweden', physical: 'iso', lang: 'sv' },
  { id: 'nb-no', name: 'Norwegian', region: 'Norway', physical: 'iso', lang: 'nb' },
  { id: 'da-dk', name: 'Danish', region: 'Denmark', physical: 'iso', lang: 'da' },
  { id: 'nl-nl', name: 'Dutch', region: 'Netherlands', physical: 'iso', lang: 'nl' },
  { id: 'pl-pl', name: 'Polish', region: 'Poland', physical: 'iso', lang: 'pl' },
  { id: 'cs-cz', name: 'Czech', region: 'Czech Republic', physical: 'iso', lang: 'cs' },
  { id: 'tr-tr', name: 'Turkish', region: 'Turkey', physical: 'iso', lang: 'tr' },
  { id: 'ar-sa', name: 'Arabic', region: 'Saudi Arabia', physical: 'iso', lang: 'ar', rtl: true },
  { id: 'he-il', name: 'Hebrew', region: 'Israel', physical: 'iso', lang: 'he', rtl: true },
  { id: 'zh-tw', name: 'Chinese (Traditional)', region: 'Taiwan', physical: 'ansi', lang: 'zh' },
];
